/*

 Copyright  2011  Mustapha Oldache   <mustapha.oldache@gmail.com>

  This file is part of Awsedit.

Awsedit is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

Awsedit is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with Awsedit.  If not, see <http://www.gnu.org/licenses/>. */


/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#ifdef HAVE_UNISTD_H
#include <unistd.h>
#endif
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)
GtkWidget *treeview;
GtkWidget *textview;
GtkWidget *statusbar;
GtkWidget *conversion;
GtkWidget *config;
GtkWidget *ouvrir;
GtkWidget *enregistrer;
GtkWidget *ebcdic_menu;
GtkWidget *ascii_menu;
GtkWidget *cobol_menu;
GtkWidget *dbf_menu;
GtkWidget *type;
GtkWidget *description;
GtkWidget *charger;
GtkWidget *sauver;
GtkWidget *rechercher;
GtkWidget *scrolledwindow1;
GtkWidget *scrolledwindow3;

GtkWidget*
create_awsedit (void)
{
  GtkWidget *awsedit;
  GtkWidget *eventbox;
  GtkWidget *fixed;
  GtkWidget *menubar;
  GtkWidget *file;
  GtkWidget *file_menu;

  GtkWidget *quitter;

  GtkWidget *extraire;
  GtkWidget *extraire_menu;


  GtkWidget *description_menu;


  GtkWidget *type_menu;
  GSList *dbf_menu_group = NULL;


  GtkWidget *options;
  GtkWidget *options_menu;
  GSList *ebcdic_menu_group = NULL;
  GtkWidget *help;
  GtkWidget *help_menu;
  GtkWidget *about;
  GtkWidget *scrolledwindow4;
  GtkWidget *scrolledwindow2;
  
  GtkAccelGroup *accel_group;
  accel_group = gtk_accel_group_new ();

  awsedit = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (awsedit), _("awsedit"));
  gtk_window_set_resizable (GTK_WINDOW (awsedit), TRUE);
  

  
  eventbox = gtk_event_box_new ();
  gtk_widget_show (eventbox);
  gtk_container_add (GTK_CONTAINER (awsedit), eventbox);

  fixed = gtk_fixed_new ();
  gtk_widget_show (fixed);
  gtk_container_add (GTK_CONTAINER (eventbox), fixed);

  menubar = gtk_menu_bar_new ();
  gtk_widget_show (menubar);
  gtk_fixed_put (GTK_FIXED (fixed), menubar, 0, 0);
  gtk_widget_set_size_request (menubar, 216, 24);

  file = gtk_menu_item_new_with_mnemonic (_("_File"));
  gtk_widget_show (file);
  gtk_container_add (GTK_CONTAINER (menubar), file);

  file_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (file), file_menu);

  ouvrir = gtk_image_menu_item_new_from_stock ("gtk-open", accel_group);
  gtk_widget_show (ouvrir);
  gtk_container_add (GTK_CONTAINER (file_menu), ouvrir);
  
  rechercher = gtk_image_menu_item_new_from_stock ("gtk-find", accel_group);
  gtk_widget_show (rechercher);
  gtk_container_add (GTK_CONTAINER (file_menu), rechercher);
  
  quitter = gtk_image_menu_item_new_from_stock ("gtk-quit", accel_group);
  gtk_widget_show (quitter);
  gtk_container_add (GTK_CONTAINER (file_menu), quitter);

  config = gtk_image_menu_item_new_from_stock ("gtk-preferences", accel_group);
  gtk_widget_show (config);
  gtk_container_add (GTK_CONTAINER (file_menu), config);
  gtk_widget_add_accelerator (config, "activate", accel_group,
                              GDK_S, (GdkModifierType) GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);
  
  extraire = gtk_menu_item_new_with_mnemonic (_("_Extract"));
  gtk_widget_show (extraire);
  gtk_container_add (GTK_CONTAINER (menubar), extraire);

  extraire_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (extraire), extraire_menu);

  conversion = gtk_check_menu_item_new_with_mnemonic (_("_Conversion"));
  gtk_widget_show (conversion);
  gtk_container_add (GTK_CONTAINER (extraire_menu), conversion);

  description = gtk_menu_item_new_with_mnemonic (_("_Description"));
  gtk_widget_show (description);
  gtk_container_add (GTK_CONTAINER (extraire_menu), description);

  description_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (description), description_menu);

  charger = gtk_menu_item_new_with_mnemonic (_("_Load"));
  gtk_widget_show (charger);
  gtk_container_add (GTK_CONTAINER (description_menu), charger);

  sauver = gtk_menu_item_new_with_mnemonic (_("_Save"));
  gtk_widget_show (sauver);
  gtk_container_add (GTK_CONTAINER (description_menu), sauver);

  type = gtk_menu_item_new_with_mnemonic (_("_Type"));
  gtk_widget_show (type);
  gtk_container_add (GTK_CONTAINER (extraire_menu), type);

  type_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (type), type_menu);

  dbf_menu = gtk_radio_menu_item_new_with_mnemonic (dbf_menu_group, _("_TRAILING SEPARATE"));
  dbf_menu_group = gtk_radio_menu_item_get_group (GTK_RADIO_MENU_ITEM (dbf_menu));
  gtk_widget_show (dbf_menu);
  gtk_container_add (GTK_CONTAINER (type_menu), dbf_menu);
  
  cobol_menu = gtk_radio_menu_item_new_with_mnemonic (dbf_menu_group, _("_IBM MScobol"));
  dbf_menu_group = gtk_radio_menu_item_get_group (GTK_RADIO_MENU_ITEM (cobol_menu));
  gtk_widget_show (cobol_menu);
  gtk_container_add (GTK_CONTAINER (type_menu), cobol_menu);
  gtk_check_menu_item_set_active (GTK_CHECK_MENU_ITEM (cobol_menu), TRUE);
  
  enregistrer = gtk_image_menu_item_new_from_stock ("gtk-media-record", accel_group);
  gtk_widget_show (enregistrer);
  gtk_container_add (GTK_CONTAINER (extraire_menu), enregistrer);

  options = gtk_menu_item_new_with_mnemonic (_("_Options"));
  gtk_widget_show (options);
  gtk_container_add (GTK_CONTAINER (menubar), options);

  options_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (options), options_menu);

  ebcdic_menu = gtk_radio_menu_item_new_with_mnemonic (ebcdic_menu_group, _("_EBCDIC"));
  ebcdic_menu_group = gtk_radio_menu_item_get_group (GTK_RADIO_MENU_ITEM (ebcdic_menu));
  gtk_widget_show (ebcdic_menu);
  gtk_container_add (GTK_CONTAINER (options_menu), ebcdic_menu);
  gtk_check_menu_item_set_active (GTK_CHECK_MENU_ITEM (ebcdic_menu), TRUE);

  ascii_menu = gtk_radio_menu_item_new_with_mnemonic (ebcdic_menu_group, _("_ASCII"));
  ebcdic_menu_group = gtk_radio_menu_item_get_group (GTK_RADIO_MENU_ITEM (ascii_menu));
  gtk_widget_show (ascii_menu);
  gtk_container_add (GTK_CONTAINER (options_menu), ascii_menu);

  help = gtk_menu_item_new_with_mnemonic (_("_Aide"));
  gtk_widget_show (help);
  gtk_container_add (GTK_CONTAINER (menubar), help);

  help_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (help), help_menu);

  about = gtk_image_menu_item_new_from_stock ("gtk-about", accel_group);
  gtk_widget_show (about);
  gtk_container_add (GTK_CONTAINER (help_menu), about);

  scrolledwindow3 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow3);
  gtk_fixed_put (GTK_FIXED (fixed), scrolledwindow3, 0, 24);
  gtk_widget_set_size_request (scrolledwindow3, 216, 440);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow3), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  scrolledwindow4 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow4);
  gtk_container_add (GTK_CONTAINER (scrolledwindow3), scrolledwindow4);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow4), GTK_SHADOW_IN);

  treeview = gtk_tree_view_new ();
  gtk_widget_show (treeview);
  gtk_container_add (GTK_CONTAINER (scrolledwindow4), treeview);

/* not generated by libglade */
GtkCellRenderer *renderer;
GtkTreeViewColumn *column;

renderer = gtk_cell_renderer_text_new ();
column = gtk_tree_view_column_new_with_attributes ("  Files      Count",
                                                   renderer,
                                                   "text", FILE_COLUMN,
                                                   NULL);
   
gtk_tree_view_append_column (GTK_TREE_VIEW (treeview), column);

column = gtk_tree_view_column_new_with_attributes ("Block   length",
                                                   renderer,
                                                   "text", BLOCK_COLUMN,
                                                   NULL);

gtk_tree_view_append_column (GTK_TREE_VIEW (treeview), column);

/* end of inserted code */
  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow1);
  gtk_fixed_put (GTK_FIXED (fixed), scrolledwindow1, 216, 24);
  gtk_widget_set_size_request (scrolledwindow1, 624, 440);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow1), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  scrolledwindow2 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow2);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), scrolledwindow2);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow2), GTK_SHADOW_IN);

  textview = gtk_text_view_new ();
  gtk_widget_show (textview);
  gtk_container_add (GTK_CONTAINER (scrolledwindow2), textview);
  gtk_text_view_set_editable (GTK_TEXT_VIEW (textview), FALSE);

  statusbar = gtk_statusbar_new ();
  gtk_widget_show (statusbar);
  gtk_fixed_put (GTK_FIXED (fixed), statusbar, 216, 0);
  gtk_widget_set_size_request (statusbar, 624, 24);

  g_signal_connect ((gpointer) ouvrir, "activate",
                    G_CALLBACK (on_ouvrir_activate),
                    NULL);
  g_signal_connect ((gpointer) rechercher, "activate",
                    G_CALLBACK (on_rechercher_activate),
                    NULL);
  g_signal_connect ((gpointer) quitter, "activate",
                    G_CALLBACK (gtk_main_quit),
                    NULL);
  g_signal_connect ((gpointer) config, "activate",
                    G_CALLBACK (on_config_activate),
                    NULL);
  g_signal_connect ((gpointer) extraire, "activate",
                    G_CALLBACK (on_extraire_activate),
                    NULL);
  g_signal_connect ((gpointer) conversion, "activate",
                    G_CALLBACK (on_conversion_activate),
                    NULL);
  g_signal_connect ((gpointer) description, "activate",
                    G_CALLBACK (on_description_activate),
                    NULL);
  g_signal_connect ((gpointer) charger, "activate",
                    G_CALLBACK (on_charger_activate),
                    NULL);
  g_signal_connect ((gpointer) sauver, "activate",
                    G_CALLBACK (on_sauver_activate),
                    NULL);
  g_signal_connect ((gpointer) dbf_menu, "activate",
                    G_CALLBACK (on_dbf_menu_activate),
                    NULL);
  g_signal_connect ((gpointer) cobol_menu, "activate",
                    G_CALLBACK (on_cobol_menu_activate),
                    NULL);
  g_signal_connect ((gpointer) enregistrer, "activate",
                    G_CALLBACK (on_enregistrer_activate),
                    NULL);
  g_signal_connect ((gpointer) options, "activate",
                    G_CALLBACK (on_options_activate),
                    NULL);
  g_signal_connect ((gpointer) ebcdic_menu, "activate",
                    G_CALLBACK (on_ebcdic_activate),
                    NULL);
  g_signal_connect ((gpointer) ascii_menu, "activate",
                    G_CALLBACK (on_ascii_activate),
                    NULL);
  g_signal_connect ((gpointer) about, "activate",
                    G_CALLBACK (on_about_activate),
                    NULL);
  g_signal_connect ((gpointer) textview, "populate_popup",
                    G_CALLBACK (on_textview_populate_popup),
                    NULL);
  g_signal_connect ((gpointer) textview, "button_release_event",
                    G_CALLBACK (on_textview_button_release_event),
                    NULL);
  g_signal_connect ((gpointer) textview, "key_release_event",
                    G_CALLBACK (on_textview_key_release_event),
                    NULL);
  g_signal_connect ((gpointer) awsedit, "configure-event",
                    G_CALLBACK (on_awsedit_configure_event),
                    NULL);
  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (awsedit, awsedit, "awsedit");
  GLADE_HOOKUP_OBJECT (awsedit, eventbox, "eventbox");
  GLADE_HOOKUP_OBJECT (awsedit, fixed, "fixed");
  GLADE_HOOKUP_OBJECT (awsedit, menubar, "menubar");
  GLADE_HOOKUP_OBJECT (awsedit, file, "file");
  GLADE_HOOKUP_OBJECT (awsedit, file_menu, "file_menu");
  GLADE_HOOKUP_OBJECT (awsedit, ouvrir, "ouvrir");
  GLADE_HOOKUP_OBJECT (awsedit, rechercher, "rechercher");
  GLADE_HOOKUP_OBJECT (awsedit, quitter, "quitter");
  GLADE_HOOKUP_OBJECT (awsedit, config, "config");
  GLADE_HOOKUP_OBJECT (awsedit, extraire, "extraire");
  GLADE_HOOKUP_OBJECT (awsedit, extraire_menu, "extraire_menu");
  GLADE_HOOKUP_OBJECT (awsedit, conversion, "conversion");
  GLADE_HOOKUP_OBJECT (awsedit, description, "description");
  GLADE_HOOKUP_OBJECT (awsedit, description_menu, "description_menu");
  GLADE_HOOKUP_OBJECT (awsedit, charger, "charger");
  GLADE_HOOKUP_OBJECT (awsedit, sauver, "sauver");
  GLADE_HOOKUP_OBJECT (awsedit, type, "type");
  GLADE_HOOKUP_OBJECT (awsedit, type_menu, "type_menu");
  GLADE_HOOKUP_OBJECT (awsedit, dbf_menu, "dbf_menu");
  GLADE_HOOKUP_OBJECT (awsedit, cobol_menu, "cobol_menu");
  GLADE_HOOKUP_OBJECT (awsedit, enregistrer, "enregistrer");
  GLADE_HOOKUP_OBJECT (awsedit, options, "options");
  GLADE_HOOKUP_OBJECT (awsedit, options_menu, "options_menu");
  GLADE_HOOKUP_OBJECT (awsedit, ebcdic_menu, "ebcdic_menu");
  GLADE_HOOKUP_OBJECT (awsedit, ascii_menu, "ascii_menu");
  GLADE_HOOKUP_OBJECT (awsedit, help, "help");
  GLADE_HOOKUP_OBJECT (awsedit, help_menu, "help_menu");
  GLADE_HOOKUP_OBJECT (awsedit, about, "about");
  GLADE_HOOKUP_OBJECT (awsedit, scrolledwindow3, "scrolledwindow3");
  GLADE_HOOKUP_OBJECT (awsedit, scrolledwindow4, "scrolledwindow4");
  GLADE_HOOKUP_OBJECT (awsedit, treeview, "treeview");
  GLADE_HOOKUP_OBJECT (awsedit, scrolledwindow1, "scrolledwindow1");
  GLADE_HOOKUP_OBJECT (awsedit, scrolledwindow2, "scrolledwindow2");
  GLADE_HOOKUP_OBJECT (awsedit, textview, "textview");
  GLADE_HOOKUP_OBJECT (awsedit, statusbar, "statusbar");

  gtk_window_add_accel_group (GTK_WINDOW (awsedit), accel_group);

  return awsedit;
}

GtkWidget *progressbar;
GtkWidget*
create_prog_bar (void)
{
  GtkWidget *prog_bar;
  GtkWidget *fixed3;


  prog_bar = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_position (GTK_WINDOW (prog_bar), GTK_WIN_POS_CENTER_ALWAYS);
  gtk_window_set_modal (GTK_WINDOW (prog_bar), TRUE);
  gtk_window_set_resizable (GTK_WINDOW (prog_bar), FALSE);
  gtk_window_set_decorated (GTK_WINDOW (prog_bar), FALSE);
  gtk_window_set_type_hint (GTK_WINDOW (prog_bar), GDK_WINDOW_TYPE_HINT_SPLASHSCREEN);

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (prog_bar), fixed3);

  progressbar = gtk_progress_bar_new ();
  gtk_widget_show (progressbar);
  gtk_fixed_put (GTK_FIXED (fixed3), progressbar, 0, 0);
  gtk_widget_set_size_request (progressbar, 480, 32);
  gtk_progress_bar_set_text (GTK_PROGRESS_BAR (progressbar), _("Lecture en cours"));

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (prog_bar, prog_bar, "prog_bar");
  GLADE_HOOKUP_OBJECT (prog_bar, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (prog_bar, progressbar, "progressbar");

  return prog_bar;
}
  GtkWidget *packed;
  GtkWidget *zoned;
  GtkWidget *supress;
  GtkWidget *annul;
GtkWidget*
create_convert_menu (void)
{
  GtkWidget *convert_menu;


  convert_menu = gtk_menu_new ();

  packed = gtk_menu_item_new_with_mnemonic (_("_Packed decimal"));
  gtk_widget_show (packed);
  gtk_container_add (GTK_CONTAINER (convert_menu), packed);

  zoned = gtk_menu_item_new_with_mnemonic (_("_Zoned decimal"));
  gtk_widget_show (zoned);
  gtk_container_add (GTK_CONTAINER (convert_menu), zoned);

  supress = gtk_menu_item_new_with_mnemonic (_("_Supress field"));
  gtk_widget_show (supress);
  gtk_container_add (GTK_CONTAINER (convert_menu), supress);

  annul = gtk_menu_item_new_with_mnemonic (_("_Annul"));
  gtk_widget_show (annul);
  gtk_container_add (GTK_CONTAINER (convert_menu), annul);

  g_signal_connect ((gpointer) packed, "activate",
                    G_CALLBACK (on_packed_activate),
                    NULL);
  g_signal_connect ((gpointer) zoned, "activate",
                    G_CALLBACK (on_zoned_activate),
                    NULL);
  g_signal_connect ((gpointer) supress, "activate",
                    G_CALLBACK (on_supress_activate),
                    NULL);
  g_signal_connect ((gpointer) annul, "activate",
                    G_CALLBACK (on_annul_activate),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (convert_menu, convert_menu, "convert_menu");
  GLADE_HOOKUP_OBJECT (convert_menu, packed, "packed");
  GLADE_HOOKUP_OBJECT (convert_menu, zoned, "zoned");
  GLADE_HOOKUP_OBJECT (convert_menu, supress, "supress");
  GLADE_HOOKUP_OBJECT (convert_menu, annul, "annul");

  return convert_menu;
}


GtkWidget *start_spin;
GtkWidget *end_spin;
GtkWidget *files_radio;
GtkWidget *blocks_radio;
GtkWidget *dos_radio;
GtkWidget *unix_radio;

GtkWidget*
create_extract_dialog (void)
{
  GtkWidget *extract_dialog;
  GtkWidget *dialog_vbox2;
  GtkWidget *fixed4;
  GtkObject *end_spin_adj;

  GtkObject *start_spin_adj;

  GtkWidget *label6;
  GtkWidget *label8;
  GtkWidget *label3;
  GtkWidget *hseparator3;
  GtkWidget *label4;
  GtkWidget *label9;

  GSList *dos_radio_group = NULL;

  GSList *files_radio_group = NULL;
  
  GtkWidget *dialog_action_area2;
  GtkWidget *extract_dialog_cancelbutton;
  GtkWidget *extract_dialog_okbutton;

  extract_dialog = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (extract_dialog), _("Extract"));
  gtk_window_set_modal (GTK_WINDOW (extract_dialog), TRUE);
  gtk_window_set_resizable (GTK_WINDOW (extract_dialog), FALSE);
  gtk_window_set_type_hint (GTK_WINDOW (extract_dialog), GDK_WINDOW_TYPE_HINT_DIALOG);

  dialog_vbox2 = GTK_DIALOG (extract_dialog)->vbox;
  gtk_widget_show (dialog_vbox2);

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_box_pack_start (GTK_BOX (dialog_vbox2), fixed4, TRUE, TRUE, 0);

  end_spin_adj = gtk_adjustment_new (1, 1, 100000, 1, 10, 10);
  end_spin = gtk_spin_button_new (GTK_ADJUSTMENT (end_spin_adj), 1, 0);
  gtk_widget_show (end_spin);
  gtk_fixed_put (GTK_FIXED (fixed4), end_spin, 168, 152);
  gtk_widget_set_size_request (end_spin, 56, 24);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (end_spin), TRUE);

  start_spin_adj = gtk_adjustment_new (1, 1, 100000, 1, 10, 10);
  start_spin = gtk_spin_button_new (GTK_ADJUSTMENT (start_spin_adj), 1, 0);
  gtk_widget_show (start_spin);
  gtk_fixed_put (GTK_FIXED (fixed4), start_spin, 168, 112);
  gtk_widget_set_size_request (start_spin, 56, 24);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (start_spin), TRUE);

  label6 = gtk_label_new (_("Type de fichier :"));
  gtk_widget_show (label6);
  gtk_fixed_put (GTK_FIXED (fixed4), label6, 0, 32);
  gtk_widget_set_size_request (label6, 112, 16);

  label8 = gtk_label_new (_("Selection"));
  gtk_widget_show (label8);
  gtk_fixed_put (GTK_FIXED (fixed4), label8, 0, 0);
  gtk_widget_set_size_request (label8, 0, 0);

  label3 = gtk_label_new (_("start"));
  gtk_widget_show (label3);
  gtk_fixed_put (GTK_FIXED (fixed4), label3, 72, 112);
  gtk_widget_set_size_request (label3, 96, 24);

  hseparator3 = gtk_hseparator_new ();
  gtk_widget_show (hseparator3);
  gtk_fixed_put (GTK_FIXED (fixed4), hseparator3, 0, 56);
  gtk_widget_set_size_request (hseparator3, 312, 24);

  label4 = gtk_label_new (_("end"));
  gtk_widget_show (label4);
  gtk_fixed_put (GTK_FIXED (fixed4), label4, 72, 152);
  gtk_widget_set_size_request (label4, 96, 24);

  label9 = gtk_label_new (_("Selection :"));
  gtk_widget_show (label9);
  gtk_fixed_put (GTK_FIXED (fixed4), label9, 24, 88);
  gtk_widget_set_size_request (label9, 80, 24);

  dos_radio = gtk_radio_button_new_with_mnemonic (NULL, _("DOS Windows"));
  gtk_widget_show (dos_radio);
  gtk_fixed_put (GTK_FIXED (fixed4), dos_radio, 120, 32);
  gtk_widget_set_size_request (dos_radio, 85, 21);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (dos_radio), dos_radio_group);
  dos_radio_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (dos_radio));
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (dos_radio), TRUE);

  unix_radio = gtk_radio_button_new_with_mnemonic (NULL, _("Unix"));
  gtk_widget_show (unix_radio);
  gtk_fixed_put (GTK_FIXED (fixed4), unix_radio, 240, 32);
  gtk_widget_set_size_request (unix_radio, 85, 21);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (unix_radio), dos_radio_group);
  dos_radio_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (unix_radio));

/* begin tuning code */
GtkWidget *radio;
  radio = gtk_radio_button_new(NULL);
  files_radio_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radio));

/* end tuning code */

  files_radio = gtk_radio_button_new_with_mnemonic (files_radio_group, _("files"));
  gtk_widget_show (files_radio);
  gtk_fixed_put (GTK_FIXED (fixed4), files_radio, 120, 88);
  gtk_widget_set_size_request (files_radio, 85, 21);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (files_radio), files_radio_group); 
  files_radio_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (files_radio));
//  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (files_radio), TRUE);

  blocks_radio = gtk_radio_button_new_with_mnemonic (files_radio_group, _("blocks"));
  gtk_widget_show (blocks_radio);
  gtk_fixed_put (GTK_FIXED (fixed4), blocks_radio, 240, 88);
  gtk_widget_set_size_request (blocks_radio, 85, 21);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (blocks_radio), files_radio_group);
  files_radio_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (blocks_radio));  
  
   


  dialog_action_area2 = GTK_DIALOG (extract_dialog)->action_area;
  gtk_widget_show (dialog_action_area2);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area2), GTK_BUTTONBOX_END);

  extract_dialog_cancelbutton = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (extract_dialog_cancelbutton);
  gtk_dialog_add_action_widget (GTK_DIALOG (extract_dialog), extract_dialog_cancelbutton, GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (extract_dialog_cancelbutton, GTK_CAN_DEFAULT);

  extract_dialog_okbutton = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (extract_dialog_okbutton);
  gtk_dialog_add_action_widget (GTK_DIALOG (extract_dialog), extract_dialog_okbutton, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (extract_dialog_okbutton, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) end_spin, "changed",
                    G_CALLBACK (on_end_spin_changed),
                    NULL);
  g_signal_connect ((gpointer) start_spin, "changed",
                    G_CALLBACK (on_start_spin_changed),
                    NULL);
  g_signal_connect ((gpointer) dos_radio, "toggled",
                    G_CALLBACK (on_dos_radio_toggled),
                    NULL);
  g_signal_connect ((gpointer) files_radio, "toggled",
                    G_CALLBACK (on_files_radio_toggled),
                    NULL);
  g_signal_connect ((gpointer) blocks_radio, "toggled",
                    G_CALLBACK (on_blocks_radio_toggled),
                    NULL);
  g_signal_connect ((gpointer) unix_radio, "toggled",
                    G_CALLBACK (on_unix_radio_toggled),
                    NULL);
  g_signal_connect ((gpointer) extract_dialog_cancelbutton, "clicked",
                    G_CALLBACK (on_extract_dialog_cancelbutton_clicked),
                    NULL);
  g_signal_connect ((gpointer) extract_dialog_okbutton, "clicked",
                    G_CALLBACK (on_extract_dialog_okbutton_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (extract_dialog, extract_dialog, "extract_dialog");
  GLADE_HOOKUP_OBJECT_NO_REF (extract_dialog, dialog_vbox2, "dialog_vbox2");
  GLADE_HOOKUP_OBJECT (extract_dialog, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (extract_dialog, end_spin, "end_spin");
  GLADE_HOOKUP_OBJECT (extract_dialog, start_spin, "start_spin");
  GLADE_HOOKUP_OBJECT (extract_dialog, label6, "label6");
  GLADE_HOOKUP_OBJECT (extract_dialog, label8, "label8");
  GLADE_HOOKUP_OBJECT (extract_dialog, label3, "label3");
  GLADE_HOOKUP_OBJECT (extract_dialog, hseparator3, "hseparator3");
  GLADE_HOOKUP_OBJECT (extract_dialog, label4, "label4");
  GLADE_HOOKUP_OBJECT (extract_dialog, label9, "label9");
  GLADE_HOOKUP_OBJECT (extract_dialog, dos_radio, "dos_radio");
  GLADE_HOOKUP_OBJECT (extract_dialog, files_radio, "files_radio");
  GLADE_HOOKUP_OBJECT (extract_dialog, blocks_radio, "blocks_radio");
  GLADE_HOOKUP_OBJECT (extract_dialog, unix_radio, "unix_radio");
  GLADE_HOOKUP_OBJECT_NO_REF (extract_dialog, dialog_action_area2, "dialog_action_area2");
  GLADE_HOOKUP_OBJECT (extract_dialog, extract_dialog_cancelbutton, "extract_dialog_cancelbutton");
  GLADE_HOOKUP_OBJECT (extract_dialog, extract_dialog_okbutton, "extract_dialog_okbutton");

  return extract_dialog;
}


GtkWidget *decimal_index_radio;
GtkWidget *index_check;
GtkWidget *hexa_index_radio;
GtkWidget *hexa_data_check;
GtkWidget *lrecl_spin;
GtkWidget*
create_config_dialog (void)
{
  GtkWidget *config_dialog;
  GtkWidget *dialog_vbox3;
  GtkWidget *_;
  GtkObject *lrecl_spin_adj;
  GtkWidget *hseparator2;
  GtkWidget *label5;

  GSList *decimal_index_radio_group = NULL;

  GtkWidget *dialog_action_area3;
  GtkWidget *config_dialog_cancelbutton;
  GtkWidget *config_dialog_okbutton;

  config_dialog = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (config_dialog), _("Configuration"));
  gtk_window_set_modal (GTK_WINDOW (config_dialog), TRUE);
  gtk_window_set_resizable (GTK_WINDOW (config_dialog), FALSE);
  gtk_window_set_type_hint (GTK_WINDOW (config_dialog), GDK_WINDOW_TYPE_HINT_DIALOG);

  dialog_vbox3 = GTK_DIALOG (config_dialog)->vbox;
  gtk_widget_show (dialog_vbox3);

  _ = gtk_fixed_new ();
  gtk_widget_show (_);
  gtk_box_pack_start (GTK_BOX (dialog_vbox3), _, TRUE, TRUE, 0);

  lrecl_spin_adj = gtk_adjustment_new (80, 4, 4750, 1, 10, 10);
  lrecl_spin = gtk_spin_button_new (GTK_ADJUSTMENT (lrecl_spin_adj), 1, 0);
  gtk_widget_show (lrecl_spin);
  gtk_fixed_put (GTK_FIXED (_), lrecl_spin, 144, 120);
  gtk_widget_set_size_request (lrecl_spin, 72, 24);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (lrecl_spin), TRUE);

  hseparator2 = gtk_hseparator_new ();
  gtk_widget_show (hseparator2);
  gtk_fixed_put (GTK_FIXED (_), hseparator2, 0, 96);
  gtk_widget_set_size_request (hseparator2, 328, 16);

  label5 = gtk_label_new (_("Record length"));
  gtk_widget_show (label5);
  gtk_fixed_put (GTK_FIXED (_), label5, 0, 120);
  gtk_widget_set_size_request (label5, 128, 16);

  hexa_data_check = gtk_check_button_new_with_mnemonic (_("hex data"));
  gtk_widget_show (hexa_data_check);
  gtk_fixed_put (GTK_FIXED (_), hexa_data_check, 248, 40);
  gtk_widget_set_size_request (hexa_data_check, 88, 21);

  index_check = gtk_check_button_new_with_mnemonic (_("index"));
  gtk_widget_show (index_check);
  gtk_fixed_put (GTK_FIXED (_), index_check, 8, 40);
  gtk_widget_set_size_request (index_check, 88, 21);

  decimal_index_radio = gtk_radio_button_new_with_mnemonic (NULL, _("decimal"));
  gtk_widget_show (decimal_index_radio);
  gtk_fixed_put (GTK_FIXED (_), decimal_index_radio, 88, 40);
  gtk_widget_set_size_request (decimal_index_radio, 85, 21);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (decimal_index_radio), decimal_index_radio_group);
  decimal_index_radio_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (decimal_index_radio));
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (decimal_index_radio), TRUE);

  hexa_index_radio = gtk_radio_button_new_with_mnemonic (NULL, _("hexa"));
  gtk_widget_show (hexa_index_radio);
  gtk_fixed_put (GTK_FIXED (_), hexa_index_radio, 168, 40);
  gtk_widget_set_size_request (hexa_index_radio, 85, 21);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (hexa_index_radio), decimal_index_radio_group);
  decimal_index_radio_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (hexa_index_radio));

  dialog_action_area3 = GTK_DIALOG (config_dialog)->action_area;
  gtk_widget_show (dialog_action_area3);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area3), GTK_BUTTONBOX_END);

  config_dialog_cancelbutton = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (config_dialog_cancelbutton);
  gtk_dialog_add_action_widget (GTK_DIALOG (config_dialog), config_dialog_cancelbutton, GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (config_dialog_cancelbutton, GTK_CAN_DEFAULT);

  config_dialog_okbutton = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (config_dialog_okbutton);
  gtk_dialog_add_action_widget (GTK_DIALOG (config_dialog), config_dialog_okbutton, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (config_dialog_okbutton, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) index_check, "toggled",
                    G_CALLBACK (on_index_check_toggled),
                    NULL);
  g_signal_connect ((gpointer) config_dialog_cancelbutton, "clicked",
                    G_CALLBACK (on_config_dialog_cancelbutton_clicked),
                    NULL);
  g_signal_connect ((gpointer) config_dialog_okbutton, "clicked",
                    G_CALLBACK (on_config_dialog_okbutton_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (config_dialog, config_dialog, "config_dialog");
  GLADE_HOOKUP_OBJECT_NO_REF (config_dialog, dialog_vbox3, "dialog_vbox3");
  GLADE_HOOKUP_OBJECT (config_dialog, _, "_");
  GLADE_HOOKUP_OBJECT (config_dialog, lrecl_spin, "lrecl_spin");
  GLADE_HOOKUP_OBJECT (config_dialog, hseparator2, "hseparator2");
  GLADE_HOOKUP_OBJECT (config_dialog, label5, "label5");
  GLADE_HOOKUP_OBJECT (config_dialog, hexa_data_check, "hexa_data_check");
  GLADE_HOOKUP_OBJECT (config_dialog, index_check, "index_check");
  GLADE_HOOKUP_OBJECT (config_dialog, decimal_index_radio, "decimal_index_radio");
  GLADE_HOOKUP_OBJECT (config_dialog, hexa_index_radio, "hexa_index_radio");
  GLADE_HOOKUP_OBJECT_NO_REF (config_dialog, dialog_action_area3, "dialog_action_area3");
  GLADE_HOOKUP_OBJECT (config_dialog, config_dialog_cancelbutton, "config_dialog_cancelbutton");
  GLADE_HOOKUP_OBJECT (config_dialog, config_dialog_okbutton, "config_dialog_okbutton");

  return config_dialog;
}

GtkWidget*
create_aboutdialog (void)
{
  GtkWidget *aboutdialog;
  const gchar *authors[] = {
    "First Name : Mustapha",
    "Last name: Oldache",
    "Title: System Engineer",
    "Mail Address : mustapha.oldache@gmail.com",
    NULL
  };
  /* TRANSLATORS: Replace this string with your names, one name per line. */
  gchar *translators = _("translator-credits");

  aboutdialog = gtk_about_dialog_new ();
  gtk_about_dialog_set_version (GTK_ABOUT_DIALOG (aboutdialog), VERSION);
  gtk_about_dialog_set_name (GTK_ABOUT_DIALOG (aboutdialog), _("Awsedit"));
  gtk_about_dialog_set_copyright (GTK_ABOUT_DIALOG (aboutdialog), _("This Program is distributed without any warranty under The GNU General Public License"));
  gtk_about_dialog_set_comments (GTK_ABOUT_DIALOG (aboutdialog), _("Awsedit lets you view and extract data from an AWS File.\n\nAwsedit was designed by Mustapha Oldache."));
  gtk_about_dialog_set_authors (GTK_ABOUT_DIALOG (aboutdialog), authors);
  gtk_about_dialog_set_translator_credits (GTK_ABOUT_DIALOG (aboutdialog), translators);

  g_signal_connect ((gpointer) aboutdialog, "response",
                    G_CALLBACK (on_aboutdialog_response),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (aboutdialog, aboutdialog, "aboutdialog");

  return aboutdialog;
}
  GtkWidget *rechercher_entry;
  GtkWidget *rechercher_dialog;
  GtkWidget *casse_check;
  GtkWidget *pos_check;
  GtkWidget *hexa_check;
  GtkWidget *rechercher_dialog_okbutton;
GtkWidget*
create_rechercher_dialog (void)
{

  GtkWidget *dialog_vbox4;
  GtkWidget *fixed5;

  GtkWidget *label7;

  GtkWidget *hseparator4;

  GtkWidget *dialog_action_area4;
  GtkWidget *rechercher_dialog_cancelbutton;


  rechercher_dialog = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (rechercher_dialog), _("Chercher"));
  gtk_window_set_type_hint (GTK_WINDOW (rechercher_dialog), GDK_WINDOW_TYPE_HINT_DIALOG);

  dialog_vbox4 = GTK_DIALOG (rechercher_dialog)->vbox;
  gtk_widget_show (dialog_vbox4);

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_box_pack_start (GTK_BOX (dialog_vbox4), fixed5, TRUE, TRUE, 0);

  rechercher_entry = gtk_entry_new ();
  gtk_widget_show (rechercher_entry);
  gtk_fixed_put (GTK_FIXED (fixed5), rechercher_entry, 104, 32);
  gtk_widget_set_size_request (rechercher_entry, 248, 24);

  label7 = gtk_label_new (_("Chercher :"));
  gtk_widget_show (label7);
  gtk_fixed_put (GTK_FIXED (fixed5), label7, 8, 32);
  gtk_widget_set_size_request (label7, 104, 16);

  casse_check = gtk_check_button_new_with_mnemonic (_("Case sensitive"));
  gtk_widget_show (casse_check);
  gtk_fixed_put (GTK_FIXED (fixed5), casse_check, 8, 80);
  gtk_widget_set_size_request (casse_check, 120, 16);

  pos_check = gtk_check_button_new_with_mnemonic (_("Restart search"));
  gtk_widget_show (pos_check);
  gtk_fixed_put (GTK_FIXED (fixed5), pos_check, 128, 80);
  gtk_widget_set_size_request (pos_check, 112, 16);

  hseparator4 = gtk_hseparator_new ();
  gtk_widget_show (hseparator4);
  gtk_fixed_put (GTK_FIXED (fixed5), hseparator4, 0, 64);
  gtk_widget_set_size_request (hseparator4, 368, 16);

  hexa_check = gtk_check_button_new_with_mnemonic (_("Hexadecimale"));
  gtk_widget_show (hexa_check);
  gtk_fixed_put (GTK_FIXED (fixed5), hexa_check, 248, 80);
  gtk_widget_set_size_request (hexa_check, 88, 21);

  dialog_action_area4 = GTK_DIALOG (rechercher_dialog)->action_area;
  gtk_widget_show (dialog_action_area4);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area4), GTK_BUTTONBOX_END);

  rechercher_dialog_cancelbutton = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (rechercher_dialog_cancelbutton);
  gtk_dialog_add_action_widget (GTK_DIALOG (rechercher_dialog), rechercher_dialog_cancelbutton, GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (rechercher_dialog_cancelbutton, GTK_CAN_DEFAULT);

  rechercher_dialog_okbutton = gtk_button_new_from_stock ("gtk-media-next");
  gtk_widget_show (rechercher_dialog_okbutton);
  gtk_dialog_add_action_widget (GTK_DIALOG (rechercher_dialog), rechercher_dialog_okbutton, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (rechercher_dialog_okbutton, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) rechercher_dialog, "close",
                    G_CALLBACK (on_rechercher_dialog_close),
                    NULL);
  g_signal_connect ((gpointer) rechercher_dialog, "delete_event",
                    G_CALLBACK (on_rechercher_dialog_delete_event),
                    NULL);
  g_signal_connect ((gpointer) rechercher_dialog, "destroy_event",
                    G_CALLBACK (on_rechercher_dialog_destroy_event),
                    NULL);
  g_signal_connect ((gpointer) rechercher_entry, "changed",
                    G_CALLBACK (on_rechercher_entry_changed),
                    NULL);
  g_signal_connect ((gpointer) rechercher_dialog_cancelbutton, "clicked",
                    G_CALLBACK (on_rechercher_dialog_cancelbutton_clicked),
                    NULL);
  g_signal_connect ((gpointer) rechercher_dialog_okbutton, "clicked",
                    G_CALLBACK (on_rechercher_dialog_okbutton_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (rechercher_dialog, rechercher_dialog, "rechercher_dialog");
  GLADE_HOOKUP_OBJECT_NO_REF (rechercher_dialog, dialog_vbox4, "dialog_vbox4");
  GLADE_HOOKUP_OBJECT (rechercher_dialog, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (rechercher_dialog, rechercher_entry, "rechercher_entry");
  GLADE_HOOKUP_OBJECT (rechercher_dialog, label7, "label7");
  GLADE_HOOKUP_OBJECT (rechercher_dialog, casse_check, "casse_check");
  GLADE_HOOKUP_OBJECT (rechercher_dialog, pos_check, "pos_check");
  GLADE_HOOKUP_OBJECT (rechercher_dialog, hseparator4, "hseparator4");
  GLADE_HOOKUP_OBJECT (rechercher_dialog, hexa_check, "hexa_check");
  GLADE_HOOKUP_OBJECT_NO_REF (rechercher_dialog, dialog_action_area4, "dialog_action_area4");
  GLADE_HOOKUP_OBJECT (rechercher_dialog, rechercher_dialog_cancelbutton, "rechercher_dialog_cancelbutton");
  GLADE_HOOKUP_OBJECT (rechercher_dialog, rechercher_dialog_okbutton, "rechercher_dialog_okbutton");

  return rechercher_dialog;
}

on_awsedit_configure_event                  (GtkWidget  *widget,
                                       GdkEventConfigure *event,
                                       gpointer user_data)
{
GtkAllocation alloctext;
GtkAllocation alloctree;
GtkAllocation allocstat;
guint x,y;
gtk_window_get_size(GTK_WINDOW(awsedit),&x,&y);

 gtk_widget_set_size_request (scrolledwindow1, x-216, y-24);
 gtk_widget_set_size_request (scrolledwindow3, 216, y-24);
 gtk_widget_set_size_request (statusbar,x-216 , 24);

 alloctree.x=0;
 alloctree.y=24;
 alloctree.width=216;
 alloctree.height=y-24;
 gtk_widget_size_allocate(scrolledwindow3,&alloctree); 
 alloctext.x=216;
 alloctext.y=24;
 alloctext.width=x-216;
 alloctext.height=y-24; 
 gtk_widget_size_allocate(scrolledwindow1,&alloctext);
 allocstat.x=216;
 allocstat.y=0;
 allocstat.width=x-216;
 allocstat.height=24;
 gtk_widget_size_allocate(statusbar,&allocstat);

 gtk_widget_queue_resize(scrolledwindow1);

 return;
}

