/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_awsedit (void);
GtkWidget* create_prog_bar (void);
GtkWidget* create_convert_menu (void);
GtkWidget* create_extract_dialog (void);
GtkWidget* create_config_dialog (void);
GtkWidget* create_aboutdialog (void);
GtkWidget* create_rechercher_dialog (void);
